runtime: node
api_version: 1
threadsafe: true
default_expiration: 1m

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*/gulpfile.js$
- ^(.*/)?.*/scss/.*$
- ^(.*/)?.*/src/.*$

handlers:
# Serve php scripts.
- url: /(.+\.js)
  script: \1
  login: required

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /fonts/(.*\.ttf)
  static_files: \1
  upload: fonts/(.*\.ttf)$
  application_readable: true

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)
  

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /ajax/(.*)\.json
  script: /ajax/\1.js


- url: /.*
  script: index.js



